- name: Start the image deploy script on Node VM
  hosts: azure
  user: azureuser
  become: yes

  tasks:

  - stat:

      path: /home/azureuser/vm_deploy_image.sh

    register: result


  - name: Copy vm_deploy_image.sh to Node

    copy:

      src: ./vm_deploy_image.sh

      dest: /home/azureuser/vm_deploy_image.sh

    when: result.stat.exists == false


  - name: Set vm_deploy_image.sh permissions

    command: chmod +x /home/azureuser/vm_deploy_image.sh


  - name: Run k8 image deploy script

    command: ./vm_deploy_image.sh
